# ecl-config
# Autogenerated from man page /usr/share/man/man1/ecl-config.1.gz
complete -c ecl-config -o cflags -d 'Output the flags required to compile a C/C++ file'
complete -c ecl-config -o ldflags -d 'Return the linker flags required to build a C/C++ application or shared libra…'
complete -c ecl-config -o libs

