# gp-2
# Autogenerated from man page /usr/share/man/man1/gp-2.13.1.gz
complete -c gp-2 -s f -l fast -d 'Fast start (or factory settings).  Do not read  '
complete -c gp-2 -s p -d '[DEPRECATED] Upon startup, gp computes a table of small primes used in number…'
complete -c gp-2 -s q -l quiet -d 'Quiet mode.  Do not print headers or history numbers and do not say goodbye'
complete -c gp-2 -s D -l default -d 'performs  default(key,  val) ";" on startup, overriding values from the  gprc…'
complete -c gp-2 -s s -d 'Size of gp internal stack allocated on startup'
complete -c gp-2 -l emacs -d 'gp can be run in an  Emacs shell (see GP User\'s manual for details)'
complete -c gp-2 -l help -d 'print a summary of available command-line options'
complete -c gp-2 -l test -d 'run gp in test mode: suppress printing of history numbers and wrap long outpu…'
complete -c gp-2 -l texmacs -d 'gp can be run from a  TeXmacs frontend'
complete -c gp-2 -l version -d 'output version info (banner) then exit'
complete -c gp-2 -l version-short -d 'output version number then exit'

