# gp
# Autogenerated from man page /usr/share/man/man1/gp.1.gz
complete -c gp -s f -l fast -d 'Fast start (or factory settings).  Do not read  '
complete -c gp -s p -d '[DEPRECATED] Upon startup, gp computes a table of small primes used in number…'
complete -c gp -s q -l quiet -d 'Quiet mode.  Do not print headers or history numbers and do not say goodbye'
complete -c gp -s D -l default -d 'performs  default(key,  val) ";" on startup, overriding values from the  gprc…'
complete -c gp -s s -d 'Size of gp internal stack allocated on startup'
complete -c gp -l emacs -d 'gp can be run in an  Emacs shell (see GP User\'s manual for details)'
complete -c gp -l help -d 'print a summary of available command-line options'
complete -c gp -l test -d 'run gp in test mode: suppress printing of history numbers and wrap long outpu…'
complete -c gp -l texmacs -d 'gp can be run from a  TeXmacs frontend'
complete -c gp -l version -d 'output version info (banner) then exit'
complete -c gp -l version-short -d 'output version number then exit'

