# gphelp
# Autogenerated from man page /usr/share/man/man1/gphelp.1.gz
complete -c gphelp -o cb -o color_bold -d 'color used for bold.  See  -color_help '
complete -c gphelp -o ch -o color_help -d 'color (between 1 and 16) used for general printing'
complete -c gphelp -o cu -o color_underline -d 'color used for underline.  See  -color_help '
complete -c gphelp -o detex -d 'Use  detex mode'
complete -c gphelp -o noskip -d 'By default, the help text is continued when a new section is tagged with a %G…'
complete -c gphelp -o utf8 -d 'In  detex mode, use UTF-8 encoding for characters, . e. g'
complete -c gphelp -s k -d 'Switch to  apropos mode'
complete -c gphelp -o raw -d 'use internal format for output (using @x markers).  For debugging only'
complete -c gphelp -o to_pod -d 'try to convert file from TeX to POD format'

