# i3lock-fancy
# Autogenerated from man page /usr/share/man/man1/i3lock-fancy.1.gz
complete -c i3lock-fancy -s h -l help -d 'Display a help screen and exit'
complete -c i3lock-fancy -s d -l desktop -d 'Attempt to minimize all windows before locking'
complete -c i3lock-fancy -s g -l greyscale -d 'Set background to greyscale instead of color'
complete -c i3lock-fancy -s p -l pixelate -d 'Pixelate the background instead of blur, runs faster'
complete -c i3lock-fancy -s f -l font -d 'Set a custom font'
complete -c i3lock-fancy -s t -l text -d 'Set a custom text prompt'
complete -c i3lock-fancy -s l -l listfonts -d 'Display a list of possible fonts for use with -f/--font'
complete -c i3lock-fancy -s n -l nofork -d 'Do not fork i3lock after starting'

