# lcalc
# Autogenerated from man page /usr/share/man/man1/lcalc.1.gz
complete -c lcalc -l rank-compute -s r -d 'Compute the analytic rank'
complete -c lcalc -l zeros-interval -d '$ lcalc --zeros-interval --x=10 --y=100 --stepsize=0'
complete -c lcalc -l zeros
complete -c lcalc -l twist-primitive -d 'should be positive'
complete -c lcalc -l twist-quadratic -d 'character modulo n.  It is an integer between 1 and phi(n)'
complete -c lcalc -l output-character
complete -c lcalc -l derivative -s d -d 'Compute the nth derivative'
complete -c lcalc -l tau -s z -d '$ lcalc --tau --zeros=10'
complete -c lcalc -s 2 -d 'computed is less than the period [bu]'
complete -c lcalc -s 1 -d '[bu] 0 for unknown [bu] 1 for periodic, including L(s,chi) [bu] 2 for cusp fo…'

