# linbox-config
# Autogenerated from man page /usr/share/man/man1/linbox-config.1.gz
complete -c linbox-config -l prefix -d 'show Linbox installation prefix'
complete -c linbox-config -l libs -d 'print library linking information'
complete -c linbox-config -l cflags -d 'print pre-processor and compiler flags'
complete -c linbox-config -l help -d 'display this help and exit'
complete -c linbox-config -l version -d 'output version information SEE ALSO The full documentation for linbox-config …'

