# mwrank
# Autogenerated from man page /usr/share/man/man1/mwrank.1.gz
complete -c mwrank -s h
complete -c mwrank -s q
complete -c mwrank -s v
complete -c mwrank -s o
complete -c mwrank -s p
complete -c mwrank -s b
complete -c mwrank -s x
complete -c mwrank -s l
complete -c mwrank -s t
complete -c mwrank -s s
complete -c mwrank -s d
complete -c mwrank -s S -s 1

