# planarity
# Autogenerated from man page /usr/share/man/man1/planarity.1.gz
complete -c planarity -s q -d 'Quiet mode'
complete -c planarity -s h -o help -d 'Display some help'
complete -c planarity -s i -o info -d 'Display copyright, license and reference articles information'
complete -c planarity -s r -d 'Run the C command (see below) on K random graphs with N vertices'
complete -c planarity -s s -d 'Run the C command (see below) on a specific graph given in the I input file, …'
complete -c planarity -o rm -d 'Compute a maximal planar random graph on N vertices with output in the primar…'
complete -c planarity -o rn -d 'Compute a nonplanar random graph (maximal planar and an edge) on N vertices w…'
complete -c planarity -s p -d 'Planar embedding and Kuratowski subgraph isolation'
complete -c planarity -s d -d 'Planar graph drawing by visibility representation'
complete -c planarity -s o -d 'Outerplanar embedding and obstruction isolation'
complete -c planarity -s 2 -d 'Search for subgraph homeomorphic to K_{2,3}'
complete -c planarity -s 3 -d 'Search for subgraph homeomorphic to K_{3,3}'
complete -c planarity -s 4 -d 'Search for subgraph homeomorphic to K_4'
complete -c planarity -s a -d 'All of the above'

