# ppl_pips
# Autogenerated from man page /usr/share/man/man1/ppl_pips.1.gz
complete -c ppl_pips -o RMB -l max-memory -d 'limits memory usage to MB megabytes'
complete -c ppl_pips -s h -l help -d 'prints this help text to stdout'
complete -c ppl_pips -o oPATH -l output -d 'appends output to PATH'
complete -c ppl_pips -s P -l polylib -d 'reads problem in PolyLib format (default)'
complete -c ppl_pips -s p -l piplib -d 'reads problem in PipLib format'
complete -c ppl_pips -s t -l timings -d 'prints timings to stderr'
complete -c ppl_pips -s v -l verbose -d 'produces lots of output'
complete -c ppl_pips -s i -l iterations -d 'executes the resolution N times (default=1)'
complete -c ppl_pips -s V -l version -d 'prints version information to stdout'
complete -c ppl_pips -o cPATH -l check -d 'checks if the result is equal to what is in PATH '
complete -c ppl_pips -s f -l cut-first -d 'uses the first non-integer row (default)'
complete -c ppl_pips -s d -l cut-deepest -d 'tries to generate the deepest cut'
complete -c ppl_pips -s a -l cut-all -d 'always generates all possible cuts . SS "Pivot row strategy options:"'
complete -c ppl_pips -s F -l row-first -d 'uses the first row with negative parameter (default)'
complete -c ppl_pips -s M -l row-max -d 'chooses row generating the lexico-maximal pivot column AVAILABILITY The lates…'

