# ppl_lcdd
# Autogenerated from man page /usr/share/man/man1/ppl_lcdd.1.gz
complete -c ppl_lcdd -o CSECS -l max-cpu -d 'limits CPU usage to SECS seconds'
complete -c ppl_lcdd -o RMB -l max-memory -d 'limits memory usage to MB megabytes'
complete -c ppl_lcdd -s h -l help -d 'prints this help text to stdout'
complete -c ppl_lcdd -o oPATH -l output -d 'appends output to PATH'
complete -c ppl_lcdd -s t -l timings -d 'prints timings to stderr'
complete -c ppl_lcdd -s v -l verbose -d 'produces lots of output'
complete -c ppl_lcdd -s V -l version -d 'prints version information to stdout'
complete -c ppl_lcdd -o cPATH -l check -d 'checks if the result is equal to what is in PATH AVAILABILITY The latest vers…'

