# tex2mail
# Autogenerated from man page /usr/share/man/man1/tex2mail.1.gz
complete -c tex2mail -o linelength -d 'Wrap text at this column'
complete -c tex2mail -o maxdef -d 'definition loops: croak if more than maxdef substitutions in a given paragraph'
complete -c tex2mail -o debug -d 'output debugging messages'
complete -c tex2mail -o by_par -d 'Expect each paragraph to be terminated by *exactly* 2 "\\\\n", and do not print…'
complete -c tex2mail -o TeX -d 'Assume input formulae are in plain TeX format'
complete -c tex2mail -o ragged -d 'leave right ragged'
complete -c tex2mail -o noindent -d 'assume \\noindent everywhere'

