[Desktop Entry]
Type=X-GNOME-Metatheme
Name=trying_to_do_something_here
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=trying_to_do_something_here
GtkTheme=trying_to_do_something_here
IconTheme=trying_to_do_something_here
MetacityTheme=trying_to_do_something_here
