#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &
nm-applet &
$HOME/.config/polybar/launch.sh
nitrogen --restore &
picom -f &

#------------ Monitor configuration ---------------------------#

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d term edit dev www chat
bspc monitor DP-1 term edit dev ww chat

#------------ Frame configuration -----------------------------#

bspc config border_width         2
bspc config window_gap          15
bspc config top_padding		35

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

#------------ Color scheme configuration ----------------------#

bspc config normal_border_color		"#121212"
bspc config active_border_color		"#121212"
bspc config focused_border_color	"#89DCEB"
bspc config presel_feedback_color	"#89DCEB"

#------------ BSPWM Rules -------------------------------------#

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Code desktop='dev'
bspc rule -a firefox desktop='www'
bspc rule -a Brave-browser-dev desktop='www'
bspc rule -a "Tor Browser" desktop='www'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a discord desktop="chat"
bspc rule -a "Spotify" desktop="music"
